#pragma once

#define VIBE_STICK_DEVICE_NAME "VibeStick"
#define FIRMWARE_NAME "vibestick"
#define FIRMWARE_VERSION "0.1.6"
#define TRANSPORT "HTTP"
#define VIBE_STICK_STATE_PATH "/state"
#define VIBE_STICK_EVENT_PATH "/event"
#define VIBE_STICK_QUOTA_REFRESH_PATH "/quota/refresh"
#define VIBE_STICK_RECORDING_START_PATH "/recording/start"
#define VIBE_STICK_RECORDING_AUDIO_PATH "/recording/audio"
#define VIBE_STICK_RECORDING_CHUNK_PATH "/recording/chunk"
#define VIBE_STICK_RECORDING_STOP_PATH "/recording/stop"
#define VIBE_STICK_STATE_POLL_MS 2000
#define VIBE_STICK_SCREEN_IDLE_MS 30000
#define VIBE_STICK_SCREEN_EVENT_WAKE_MS 20000
#define VIBE_STICK_AUTO_POWER_OFF_MS (60LL * 60LL * 1000LL)
#define VIBE_STICK_IMU_POLL_MS 100
#define VIBE_STICK_FACE_DOWN_HOLD_MS 800
#define VIBE_STICK_FACE_UP_HOLD_MS 500
#define VIBE_STICK_FACE_DOWN_Z_THRESHOLD_G (-0.72f)
#define VIBE_STICK_FACE_UP_Z_THRESHOLD_G 0.60f
#define VIBE_STICK_FACE_DOWN_XY_LIMIT_G 0.70f
#define VIBE_STICK_PICKUP_DELTA_G 0.08f
#define VIBE_STICK_PICKUP_STRONG_DELTA_G 0.18f
#define VIBE_STICK_PICKUP_CONFIRM_SAMPLES 2
#define VIBE_STICK_RECORDING_CHUNK_INTERVAL_MS 120
#define VIBE_STICK_RECORDING_CHUNK_BYTES 3840
#define VIBE_STICK_RECORDING_RELEASE_DEBOUNCE_MS 80
#define VIBE_STICK_RECORDING_MAX_MS 115000

#if __has_include("vibe_stick_secrets.h")
#include "vibe_stick_secrets.h"
#else
#define VIBE_STICK_WIFI_SSID ""
#define VIBE_STICK_WIFI_PASSWORD ""
#define VIBE_STICK_BRIDGE_HOST "127.0.0.1"
#define VIBE_STICK_BRIDGE_PORT 8765
#endif

#ifndef VIBE_STICK_BRIDGE_TOKEN
#define VIBE_STICK_BRIDGE_TOKEN ""
#endif
